name: dataform_execution

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    # Allow the job to fetch a GitHub ID token
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.3.1'
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/886273328813/locations/global/workloadIdentityPools/workload-identity-pool-id/providers/github-actions"'
          service_account: 'test-sc@morioka-personal.iam.gserviceaccount.com'
      
      - name: 'Set up Cloud SDK'
        uses: "google-github-actions/setup-gcloud@v0"

      - name: 'Use gcloud CLI'
        run: 'gcloud workflows run workflow-1'
